### PR TITLE
Update paypal-models.ts

### PR DESCRIPTION
**Pull request by gh-vaishnavi**
Need to pass custom_id while using CreateSubscription

### CODE REVIEW

**Review by vaishnavi-gh — COMMENTED** [review]
Need to pass custom_id while using CreateSubscription

**Comment by vaishnavi-gh** [comment]
Awaiting for nmp package update

**Comment by cacalo** [comment]
It's a shame that this PR hasn't been merged yet! :(

**Comment by Enngage** [comment]
@cacalo hey, no need to fork, you can just use `any` type in Typescript and you're good to go. Sure, it's not ideal, but sometimes you have no better choice.

**Pull request merged**
