### PR TITLE
Feature/create subscription callback

### PR DESCRIPTION
**Pull request by silleknarf**
- Fixing a major bug in that only one of createSubscription and createOrder can be passed through to the button config
- Adding proper support for the vault parameter
- Making the onShippingChange callback optional (as it's unsupported in the sandbox for subscriptions)

### CODE REVIEW

**Comment by Enngage** [comment]
Hi, is this ready to be merged? :)

**Comment by silleknarf** [comment]
Yes it's good to go in 👍

**Comment by mystery-man** [comment]
@Enngage Is it going to be merged soon ? Really need this subscription stuff asap.

**Comment by wgcv** [comment]
Thanks all! I'm waiting this update in npm! ✨

**Comment by Enngage** [comment]
Hey, I've just released it. Thanks!

**Pull request merged**
